#!/usr/bin/bash

if [ "$(id -u)" -gt 0 ]; then
    echo "Must be run as root, exiting..."
    exit 1
fi

INTERFACE=$1
DOMAIN=$2

if [ -z "$DOMAIN" ]; then
    DOMAIN=incus
fi

if [ -z "$INTERFACE" ]; then
    echo "No interface specified, exiting..."
    exit 1
fi

ADDRESS=$(incus network show "$1" | grep ipv4.address | cut -d : -f 2 | cut -d / -f 1)

if [ -z "$ADDRESS" ]; then
    echo "No ipv4 address returned, exiting..."
    exit 1
fi

sudo tee /etc/systemd/system/incus-dns-"$INTERFACE".service << EOF
[Unit]
Description=Incus per-link DNS configuration for $INTERFACE 
BindsTo=sys-subsystem-net-devices-$INTERFACE.device
After=sys-subsystem-net-devices-$INTERFACE.device

[Service]
Type=oneshot
ExecStart=/usr/bin/resolvectl dns $INTERFACE $ADDRESS
ExecStart=/usr/bin/resolvectl domain $INTERFACE $DOMAIN
ExecStopPost=/usr/bin/resolvectl revert $INTERFACE 
RemainAfterExit=yes

[Install]
WantedBy=sys-subsystem-net-devices-$INTERFACE.device
EOF

/usr/bin/firewall-cmd --zone=trusted --change-interface="$INTERFACE" --permanent
/usr/bin/systemctl daemon-reload
/usr/bin/systemctl enable --now incus-dns-"$INTERFACE".service
